sudo: true
language: python
addons:
 apt:
  packages:
   - libgmp-dev
python:
 - "2.6"
 - "2.7"
install:
 - "pip install scrypt twofish"
 - "python setup.py install"
script:
 - "python setup.py test"
notifications:
 irc: "irc.kassala.de#pol"
