language: python
python:
 - "2.7"
install:
 - "sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm"
 - "sudo apt-get install libgmp-dev"
 - "echo git describe"
 - "python setup.py install"
script:
 - "python setup.py test"
