sudo: false
language: python
addons:
 apt:
  packages:
   - libgmp-dev
python:
 - "2.6"
 - "2.7"
install:
 - "echo 'travis' > RELEASE-VERSION"
 - "pip install scrypt"
 - "python setup.py install"
script:
 - "python setup.py test"
notifications:
 irc: "irc.kassala.de#pol"
