dist: xenial # required for Python >= 3.7
language: python
python:
 - "3.6"
 - "3.7"
install:
 - "sudo apt-get update -qq"
 - "sudo apt-get install libgmp-dev libmpfr-dev libmpc-dev"
 - "pip install scrypt twofish"
 - "python setup.py install"
script:
 - "python setup.py test"
notifications:
 irc: "irc.kassala.de#pol"
