language: python
python:
 - "2.6"
 - "2.7"
install:
 - "sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm"
 - "sudo apt-get install -qq libgmp-dev libmcrypt-dev"
 - "echo 'travis' > RELEASE-VERSION"
 - "python setup.py install"
script:
 - "python setup.py test"
notifications:
 irc: "irc.kassala.de#pol"
